#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..

source script/common

info "Locating installers\n"

# find the installers and run them iteratively
installers=$(find . -mindepth 2 -name install.sh)
for installer in $installers; do
    info "Running ${installer}\n"
    sh -ic "${installer}"
done

sh -c "script/bootstrap"
